spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  cache:
    type: redis
    redis:
      host: 127.0.0.1
      port: 6379
logging:
  level:
    com.ll.exam.com.ll.exam.spring_restapi.app: debug
custom:
  jwt:
    secretKey: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey